version: 2.1

commands:
  install-python-dev-tools:
    steps:
      # See: https://circleci.com/docs/ja/2.0/language-python/#%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5
      - restore_cache:
          key: &cache-key-pipenv cache-pipenv-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "Pipfile" }}
      - run:
          name: Install python dev tools
          command: |
            apt-get update
            apt-get install -y ca-certificates python3-pip
            pip3 install pipenv
            pipenv install --dev -e .
          environment:
            PIPENV_VENV_IN_PROJECT: true
      - save_cache:
          key: *cache-key-pipenv
          paths:
            - ".venv"
            - "Pipfile.lock"
            - "/usr/local/bin"
            - "/usr/local/lib/python*/site-packages"

  prepare-github-writable-user:
    steps:
      - run:
          name: Configure git user
          command: |
            git config user.email "bot+actfw-core-ci@idein.jp"
            git config user.name "ideinbot"
      - add_ssh_keys:
          fingerprints:
            - "1b:7a:57:1b:eb:5d:b8:c4:cd:02:e2:d2:81:d8:65:ee"

jobs:
  lint:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - run:
          name: Check code format
          command: |
            [ $(pipenv run autopep8 --diff --max-line-length 128 -r . | wc -l) = 0 ]

  test:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - run:
          name: nose2
          command: pipenv run nose2 -v

  build-api-doc:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - run:
          name: sphinx-build
          command: |
            pipenv run sphinx-build docs build/sphinx/html
      - persist_to_workspace:
          root: build/sphinx
          paths:
            - html

  build-package:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - run:
          name: Make wheel & sdist
          command: |
            pipenv run python setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: .
          paths:
            - dist

  validate-version-with-tag:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - run:
          name: Check if git tag name is appropriate for package version
          command: |
            export TAG=$(echo ${CIRCLE_TAG} |sed -e 's/release-//')
            export VERSION=$(pipenv run python -c 'import actfw_core; print(actfw_core.__version__)')
            echo "Git tag: $TAG"
            echo "Package version: $VERSION"
            test "$VERSION" = "$TAG"

  deploy-api-doc:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: checkout gh-pages branch
          command: git checkout gh-pages-test
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Place doc contents in version directory (linked by `latest` symlink)
          command: |
            export TAG=$(echo ${CIRCLE_TAG} |sed -e 's/release-//')
            rm -rf $TAG latest
            mkdir $TAG
            cp -rf /tmp/workspace/html/* $TAG/
            ln -s $TAG latest
      - prepare-github-writable-user
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            git add .
            git commit -m '[skip ci] updates API doc'
            git push origin gh-pages-test

  deploy-package:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - install-python-dev-tools
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Publish wheel & sdist to PyPI
          command: |
            pipenv run python -m twine upload --non-interactive --repository pypi /tmp/workspace/dist/*
          environment:
            - TWINE_USERNAME: ideinbot
            - TWINE_PASSWORD: $PYPI_PASSWORD

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
      - build-api-doc
      - build-package
  release:
    jobs:
      - validate-version-with-tag:
          filters:
            tags:
              only: /^release-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - build-api-doc:
          requires:
            - validate-version-with-tag
          filters:
            tags:
              only: /^release-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - build-package:
          requires:
            - validate-version-with-tag
          filters:
            tags:
              only: /^release-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - deploy-api-doc:
          requires:
            - build-api-doc
          filters:
            tags:
              only: /^release-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - deploy-package:
          requires:
            - build-package
          filters:
            tags:
              only: /^release-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
